SUCCESS = "SUCCESS"
ALREADY_DONE = "ALREADY_DONE"
READY_TO_SIGN = "READY_TO_SIGN"
SESSION_EXPIRED = "SESSION_EXPIRED"
ERROR = "ERROR"
UNKNOWN = "UNKNOWN"

TERMINAL_STATUSES = {SUCCESS, ALREADY_DONE}
NOTIFY_STATUSES = {SESSION_EXPIRED}
